<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%LIKE' => '',
    '%LIKE%' => '',
    '=' => '',
    'Create' => '',
    'Create Field' => '',
    'Field ID' => '',
    'Field order' => '',
    'Field order: ' => '',
    'Fields' => '',
    'Filter  type' => '',
    'ID' => '',
    'Loan' => '',
    'Loan create form' => '',
    'Loan edit form' => '',
    'Loan table' => '',
    'Loan view table' => '',
    'Name' => '',
    'No' => '',
    'Order' => '',
    'Order fields' => '',
    'Person' => '',
    'Person create form' => '',
    'Person edit form' => '',
    'Person table' => '',
    'Person view table' => '',
    'Role' => '',
    'Show' => '',
    'Sort Order' => '',
    'Type' => '',
    'Update' => '',
    'Update field order' => '',
    'Update {modelClass}: ' => '',
    'View' => '',
    'Yes' => '',
    'Enable' => '@@@@',
    'Enable in form' => '@@Show form@@',
    'Enable in table' => '@@Show table@@',
];
