<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All' => '',
    'Amount' => '',
    'Approved' => '',
    'Bank 1' => '',
    'Bank 1 won' => '',
    'Bank 2' => '',
    'Bank 2 won' => '',
    'Bank 3' => '',
    'Canceled' => '',
    'Close Time' => '',
    'Close time' => '',
    'Closed' => '',
    'Communication data / notes' => '',
    'Create' => '',
    'Create loan' => '',
    'Create person' => '',
    'Deal Stage' => '',
    'Deal product' => '',
    'Description' => '',
    'Edit loan' => '',
    'First payment' => '',
    'ID' => '',
    'In progress' => 'In the process',
    'Ip Ountry' => '',
    'Is Call' => '',
    'Is Email' => '',
    'Is Sms' => '',
    'Is statement' => '',
    'Is vsaa' => '',
    'Loan data' => 'Loan data',
    'Loan delete disabled.' => '',
    'Loans' => '',
    'Manual' => '',
    'More information' => '',
    'Negative' => '',
    'New' => '',
    'None' => '',
    'Person ID' => '',
    'Person data' => 'Personal information',
    'Positive' => '',
    'Product' => '',
    'Product 1' => '',
    'Product 2' => '',
    'Product 3' => '',
    'Query String' => '',
    'Received' => '',
    'Refferal' => '',
    'Rejected' => '',
    'Source' => 'Source',
    'Status' => '',
    'Term' => 'Loan term',
    'Update' => '',
    'Update Time' => '',
    'User ID' => '',
    'Waiting Time' => '',
    'Waiting for data' => '',
    'Are you sure you want to delete this item?' => '@@@@',
    'Create Loan' => '@@@@',
    'Delete' => '@@@@',
    'Update {modelClass}: ' => '@@@@',
	'Waiting BS' => '',
	'Waiting extra info' => 'Waiting information',
	'Refuses' => '',
	'Paid out' => '',
	'Keep working' => 'Keep on working',
    'Send SMS to Customers' => '',
    'Nav oficiāla darba' => 'No official job',
    'Dekrētā' => 'On maternity leave',
    'credit' => 'Credit',
    'Document' => 'Document',
    'Accepted' => 'Accepted',
    

// Sources
	'placis' => 'Placek!!',
	'Aizdevumu refinansēšana' => 'Refinancing of loans',
	'Kredīts pret automašīnas ķīlu' => 'Credit against a car collateral',
	'Kredīts pret nekustamo īpašumu' => 'Real Estate Loan',
	'Kredīts uzņēmējdarbībai' => 'Business Credit',
	'Online aizdevums līdz 1500 eiro' => 'Online loan up to 1500 euros',
	'Patēriņa kredīts' => 'Consumer credit',

	'Рефинансирование кредитов' => 'Refinancing of loans',
	'Кредит под залог автомобиля' => 'Credit against a car collateral',
	'Кредит под залог недвижимости' => 'Real Estate Loan',
	'Кредит для бизнеса' => 'Business Credit',
	'Онлайн кредит до 1500 евро' => 'Online loan up to 1500 euros',
	'Потребительский кредит' => 'Consumer credit',

    'Person Name' => 'Name',
    'Person Surname' => 'Surname',
    'Person Personal Code' => 'Personal code',
    'Person Email' => 'e-mail',
    'Person Phone' => 'Phone',
    'Progress' => 'Progress',

    'Notes' => 'Notes',
    'Kurjers' => 'Courier',
    'Sazvanīts' => 'A call to a customer',
    'Neatbild' => 'Сlient does not answer',
    'Veikto zvanu skaits' => 'Number of made calls',
    'Change status' => '',
    'Start typing to leave a note...' => '',
    'Loan extra data' => 'ADDITIONAL INFO',
    'Create date' => 'Application creation time',
    'source' => 'TYPE OF CREDIT',
    'Loan amount' => '',
    'property_address' => 'Property address',
    'Company Name' => '',
    'Autoregnr' => 'Registration number',

    'Approved amount' => '',
    'Issued amount' => 'Izsniegtā summa',
    'Сustomer declined' => 'Сustomer declined',

    'Real Estate' => 'THE CLIENT OWNS THE PROPERTY',

    'amount_taken' => 'Factoring amount',
    'Revenue' => 'Company turnover',
    'Company in operation' => '',
    'Test' => '',
    'Create Time' => 'Application creation time',
    'Update Loan Data' => 'Update loan data',

    'Paid' => '',
    'Insurance' => '',
    'Deposits' => '',

    'Search' => '',

    'Accepted loans' => '',

    'Manager ID' => '',
    'Manager' => '',

    'Add appointment' => '',
    'Edit appointment' => '',
    'Set appointment date.' => '',
    

];
