<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array_map(function($value) {
    return mb_strtoupper($value, 'UTF-8');
}, [
    'Create' => '',
    'Create Time' => '',
    'Credit History' => '',
    'Dependants' => 'Dependants',
    'Description' => '',
    'Edit person' => '',
    'Email' => 'E-mail',
    'ID' => '',
    'Income' => 'Monthly income',
    'Loan count' => '',
    'Name' => 'First name',
    'Notes' => '',
    'Outcome' => 'Payment on existing loans',
    'People' => '',
    'Person delete disabled.' => '',
    'Personal Code' => '',
    'Phone' => 'Phone',
    'Surname' => '',
    'Update' => '',
    'Update Time' => '',
    'Are you sure you want to delete this item?' => '@@@@',
    'Create Person' => '@@@@',
    'Delete' => '@@@@',
    'Update {modelClass}: ' => '@@@@',

    'Full declared address' => 'Declared place of residence',
    'Workplace' => 'Place of work',
    'Length of service at last job (months)' => 'Darba pieredze (mēn.)',
    'Marital Status'  =>'Marital Status',
    'Lastname' => 'Surname',
    'Personal Code'=>'Personal Code',
    'city'=>'city',
    'Position'=>'Position',
    'Length Of Service'=>'Length Of Service',
    'Company Name'=>'Company Name'
]);
