<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => '',
    'Calendar' => '',
    'Home' => '',
    'Loan' => '',
    'Logout' => '',
    'Person' => '',
    'Stats' => '',
    'Dashboard' => '',
    'Loans' => '',
    'Appointment' => 'Coordinated meetings',
    'Contacts' => '',
    'Info' => '',
	'note_data_based_on_create_time' => 'Note: This data is based on create_time but paid out count is based on close_time.',
    'load_more' => 'Загрузи больше',
    'Templates' => '',
    'Chat' => '',
    'Settings' => '',

    'footer_copyright' => '&copy; 2016-2022. All rights reserved.',
    'footer_website' => 'www.finlat.lv.',
    'footer_company_name' => 'E-COMMERCE BROKER SIA.',
    'footer_address' => 'Stabu street 50-13, Riga, Latvia.',
    'footer_phone' => 'Phone: +371 27 555 555.',

    'Calculators' => '',


];
