<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin log' => '@@Logi@@',
    'Admin fields' => 'Lauki',
    'Admin index' => 'Administratora panelis',
    'Admin logs' => 'Logi',
    'Admin modules' => 'Moduļi',
    'Fields' => 'Lauki',
    'Index' => 'Panelis',
    'Logs' => 'Logi',
    'Modules' => 'Moduļi',
    'Settings' => 'Iestatījumi',
    'Users' => 'Lietotāji',
     'Partial Data' => 'Daļēji dati',
    'Providers' => '',
    'Sources' => 'Avoti',

    'Clear cache' => 'Izdzēst kešatmiņu',
    'Clear export cache' => 'Izdzēst eksporta kešatmiņu',
    'Others' => 'Citi',
];
