<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%LIKE' => '',
    '%LIKE%' => '',
    '=' => '',
    'Field ID' => '',
    'Field order' => '',
    'Field order: ' => '',
    'Loan create form' => '',
    'Loan edit form' => '',
    'Loan table' => '',
    'Loan view table' => '',
    'Order fields' => '',
    'Person create form' => '',
    'Person edit form' => '',
    'Person table' => '',
    'Person view table' => '',
    'Show' => '',
    'Sort Order' => '',
    'Update field order' => '',
    'View' => '',
    'Enable in form' => '@@Rādīt formā@@',
    'Enable in table' => '@@Rādīt tabulā@@',
    'Create' => 'Izveidot',
    'Create Field' => 'Izveidot lauku',
    'Fields' => 'Lauki',
    'Filter  type' => 'Filtrēšanas veids',
    'ID' => 'ID',
    'Loan' => 'Kredīts',
    'Name' => 'Nosaukums',
    'No' => 'Nē',
    'Order' => 'Secība',
    'Person' => 'Klients',
    'Role' => 'Tiesības',
    'Type' => 'Tips',
    'Update' => 'Labot',
    'Update {modelClass}: ' => 'Labot lauku ',
    'Yes' => 'Jā',
];
