<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
function TranslationsToUppercase($translations) {
    foreach ($translations as $key => $value) {
        $translations[$key] = mb_strtoupper($value, 'UTF-8');
    }
    return $translations;
}
return TranslationsToUppercase ([
    'Are you sure you want to delete this item?' => '@@Vai tiešām dzēst?@@',
    'Create Person' => '@@Izveidot personu@@',
    'Delete' => '@@Dzēst@@',
    'Update {modelClass}: ' => '@@Labot klientu: @@',
    'Create' => 'Izveidot',
    'Create Time' => 'Izveidošanas laiks',
    'Credit History' => 'Kredītu vēsture',
    'Dependants' => 'Apgādājamie',
    'Description' => 'Apraksts',
    'Edit person' => 'Labot klientu',
    'Email' => 'E-pasts',
    'ID' => 'ID',
    'Income' => 'Mēneša ienākumi',
    'Loan count' => 'Kredītu skaits',
    'Name' => 'Vārds',
    'Notes' => 'Piezīmes',
    'Outcome' => 'Esošo aizdevumu maksājumi',
    'People' => 'Klienti',
    'Person delete disabled.' => 'Klientu dzēšana izslēgta.',
    'Personal Code' => 'Personas kods',
    'PERSON DATA'=>'PERSONAS DATI',
    'LEGAL PERSON DATA' =>'JURIDISKĀS PERSONAS DATI',
    'Phone' => 'Tālrunis',
    'Surname' => 'Uzvārds',
    'Update' => 'Labot',
    'Create date' => 'Izveidošanas laiks',
    'Update date' => 'Labošanas laiks',
    'Family status' => 'Ģimenes stāvoklis',
    'Education' => 'Izglītība',
    'Accept Email' => 'Pieņem epastus',
    'Loan count 6 months' => 'Kredītu skaits 6 mēnešos',
    'Workplace' => 'Darba vietas nosaukums',
    'Position' => 'Ieņemamais amats',
    'Length Of Service' => 'Darba pieredze (mēn.)',
    'Privacy' => 'Privātums',
    'Address' => 'Pilna deklarētā adrese',
    'Salary' => 'Atalgojums',
    'Annual Turnover' => 'Gada apgrozījums',
    'Working Time' => 'Darba stāžs',
    'Town' => 'Pilsēta',
    'Full declared address' => 'Deklarētā dzīvesvietas adrese',
    'Lastname' => 'Uzvārds',
    'Company Turnover' => 'UZŅĒMUMA APGROZĪJUMS',
    'Registration Number' => 'Reģistrācijas numurs',
    'Company Name' => 'UZŅĒMUMA NOSAUKUMS',
    'Company Work Month'=>' UZŅĒMUMA DARBĪBAS ILGUMS(MĒN.)',
    'Marital Status'  =>'Ģimenes stāvoklis',
    'city'=>'PILSĒTA',
    // 'CHANGES MADE'=>'VEIKTAS IZMAIŅAS',
]);
