<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Administrēšana',
    'Calendar' => 'Kalendārs',
    'Home' => 'Sākums',
    'Loan' => 'Kredīti',
    'Logout' => 'Iziet',
    'Person' => 'Klienti',
    'Stats' => 'Statistika',
    'note_data_based_on_create_time' => 'Piezīme: Šie dati ir balstīti uz create_time, bet apmaksātais skaits ir balstīts uz close_time.',
    'load_more' => 'Ielādēt vairāk',
    'Language' => 'Valoda',
    'Loans' => 'Aizņēmumi',
    'Dashboard' => 'Mērinstrumentu panelis',
    'Info' => 'Informācija',
    'Appointment' => 'Saskaņotās tikšanās',
    'Contacts' => 'Informācija',
    'Templates' => 'Šabloni',
    'Chat' => 'Čats',
    'Settings' => 'Iestatījums',

    'footer_copyright' => '&copy; 2016-2022. Visas tiesības aizsargātas.',
    'footer_website' => 'www.finlat.lv.',
    'footer_company_name' => 'E-COMMERCE BROKER SIA.',
    'footer_address' => 'Stabu iela 50-13, Rīga, Latvija.',
    'footer_phone' => 'Tālrunis: +371 27 555 555.',

    'Calculators' => 'Kalkulatori',


];
