<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Administrātors',
    'Are you sure you want to delete this item?' => 'Tiešām dzēst?',
    'Auth' => 'Autorizācijas vērtība',
    'Change password' => 'Mainīt paroli',
    'Create' => 'Izveidot',
    'Create Time' => 'Izveidošanas laiks',
    'Create User' => 'Izveidot lietotāju',
    'Delete' => 'Dzēst',
    'Email' => 'E-pasts',
    'Fullname' => 'Pilnais vārds',
    'ID' => 'ID',
    'Password' => 'Parole',
    'Role' => 'Tiesības',
    'Update' => 'Labot',
    'Update Time' => 'Labošanas laiks',
    'Update {modelClass}: ' => 'Labot lietotāju: ',
    'User' => 'Lietotājs',
    'Users' => 'Lietotāji',

    'Provider id' => 'Partner',

    'Chat Enable' => 'Iespējot tērzēšanu',
    'Upload avatar' => 'Augšupielādējiet avatāru',
    'Avatar' => 'Iemiesojums',

    'Picture' => 'Attēls',
    'Delete avatar' => 'Dzēst avatāru',

    'Login' => 'Autentifikācija',
];
