<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin log' => 'Лог администратора',
    'Admin fields' => 'Поля для администратора',
    'Admin index' => 'Панель администратора',
    'Admin logs' => 'Логи администратора',
    'Admin modules' => 'Модули администратора',
    'Fields' => 'Поля',
    'Index' => 'Панель',
    'Logs' => 'Логи',
    'Modules' => 'Модули',
    'Settings' => 'Настройки',
    'Users' => 'Пользователи',
    'Partial Data' => 'Частичные данные',
    'Providers' => 'Партнеры',
    'Sources' => 'Источники',

    'Clear cache' => 'Очистить кэш',
    'Clear export cache' => 'Очистить кэш экспорта',
    'Others' => 'Другие',
];
