<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%LIKE' => '%LIKE%',
    '%LIKE%' => '%LIKE%',
    '=' => '=',
    'Field ID' => 'Идентификатор поля',
    'Field order' => 'Порядок полей',
    'Field order: ' => 'Порядок полей: ',
    'Loan create form' => 'Форма для создания займа',
    'Loan edit form' => 'Форма для редактирования займа',
    'Loan table' => 'Таблица займа',
    'Loan view table' => 'Таблица просмотра займа',
    'Order fields' => 'Поля заказов',
    'Person create form' => 'Форма для создания лица',
    'Person edit form'  => 'Форма для редактирования лица',
    'Person table' => 'Таблица лица',
    'Person view table' => 'Таблица просмотра лица',
    'Show' => 'Показать',
    'Sort Order' => 'Порядок сортировки',
    'Update field order' => 'Обновить порядок полей',
    'View' => 'Просмотр',
    'Enable in form' => 'Разрешить в форме',
    'Enable in table' => 'Разрешить в таблице',
    'Create' => 'Создать',
    'Create Field' => 'Создать поле',
    'Fields' => 'Поля',
    'Filter  type' => 'Тип фильтра',
    'ID' => 'ID',
    'Loan' => 'Заем',
    'Name' => 'Имя',
    'No' => 'Нет',
    'Order' => 'Заказ',
    'Person' => 'Лицо',
    'Role' => 'Роль',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
    'Yes' => 'Да',
];
