<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Time' => 'Время создания',
    'Data' => 'Данные',
    'Export data' => 'Экспорт данных',
    'Failed login' => 'Неудачная попытка входа',
    'ID' => 'ID',
    'Logs' => 'Логи',
    'Success login' => 'Успешный вход',
    'System update' => 'Обновление системы',
    'Type' => 'Тип,',
    'Update Time' => 'Время обновления',
    'User created' => 'Пользователь создан',
    'User updated' => 'Пользователь обновлен',
    'Are you sure you want to delete this item?' => 'Удалить этот пункт?',
    'Create' => 'Создать',
    'Create Log' => 'Создать лог',
    'Delete' => 'Удалить',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
];
