<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
function TranslationToUppercase($translations) {
    foreach ($translations as $key => $value) {
        $translations[$key] = mb_strtoupper($value, 'UTF-8');
    }
    return $translations;
}
return TranslationToUppercase ([
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Create Person' => 'Создать лицо',
    'Delete' => 'Удалить',
    'Update {modelClass}: ' => 'Обновление {modelClass}: ',
    'Create' => 'Создать',
    'Create Time' => 'Время создания',
    'Credit History' => 'Кредитная история',
    'Lastname' => 'Фамилия',
    'Description' => 'Описание',
    'Edit person' => 'Изменить клиента',
    'Email' => 'Электронная почта',
    'ID' => 'ID',
    'Income' => 'Ежемесячные доходы',
    'Loan count' => 'Число займов',
    'Name' => 'Имя',
    'Notes' => 'Записи',
    'Outcome' => 'Платеж по существующим кредитам',
    'People' => 'Люди',
    'Person delete disabled.' => 'Удаление лица отключено.',
    'Personal Code' => 'Персональный код',
    'Phone' => 'Телефон',
    'Surname' => 'Фамилия',
    'Update' => 'Обновить',
    'Update Time' => 'Время обновления',
    'Person Name' => 'Имя',
    'Person Phone' => 'Телефон',
	'Dependants' => 'Иждивенцы',
    'PERSON DATA'=>'ПЕРСОНАЛЬНЫЕ ДАННЫЕ',
    'LEGAL PERSON DATA' =>'ДАННЫЕ ЮРИДИЧЕСКОГО ЛИЦА',
    'Create date' => 'Время создания',
    'Update date' => 'Время коррекции',
    'Family status' => 'Семейное положение',
    'Education' => 'Образование',
    'Accept Email' => 'Принимает электронные письма',
    'Loan count 6 months' => 'Количество кредитов за 6 месяцев',
    'Workplace' => 'Место работы',
    'Position' => 'Должность',
    'Length Of Service' => 'Стаж работы (месяцев)',
    'Privacy' => 'Политика конфиденциальности',
    'Address' => 'Полный заявленный адрес',
    'Salary' => 'Оплата',
    'Annual Turnover' => 'Ежегодный оборот',
    'Working Time' => 'Опыт работы',
    'Town' => 'Город',
    'Full declared address' => 'Декларированное место жительства',
    'Marital Status'=>'Семейное положение',
    'Company Turnover' => 'ОБОРОТ КОМПАНИИ',
    'Registration Number' =>'Регистрационный номер',
    'Company Name' => 'НАЗВАНИЕ ПРЕДПРИЯТИЯ',
    'Company Work Month'=>'КОМПАНИЯ РАБОТАЕТ (МЕС.)',
     'city'=>'ГОРОД',
]);
