<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Администратор',
    'Calendar' => 'Календарь',
    'Home' => 'Главная',
    'Loan' => 'Кредит',
    'Logout' => 'Выйти',
    'Person' => 'Лицо',
    'Stats' => 'Статистика',
    'note_data_based_on_create_time' => 'Примечание: эти данные основаны на create_time, но количество выплат основано на close_time.',
	'load_more' => 'Загрузи больше',
    'Language' => 'Язык',
    'Loans' => 'Кредиты',
    'Dashboard' => 'Рабочий стол',
    'Info' => 'Информация',
    'Appointment' => 'Согласованные встречи',
    'Contacts' => 'Контакты',
    'Templates' => 'Шаблоны',
    'Chat' => 'Чат',
    'Settings' => 'Настройки',

    'footer_copyright' => '&copy; 2016-2022. Все права защищены.',
    'footer_website' => 'www.finlat.lv.',
    'footer_company_name' => 'E-COMMERCE BROKER SIA.',
    'footer_address' => 'ул. Стабу 50-13, Рига, Латвия.',
    'footer_phone' => 'Телефон: +371 27 555 555.',

    'Calculators' => 'Калькуляторы',

];
