<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Администратор',
    'Are you sure you want to delete this item?' => 'Удалить этот пункт?',
    'Auth' => 'Авторизация',
    'Change password' => 'Изменить пароль',
    'Create' => 'Создать',
    'Create Time' => 'Время создания',
    'Create User' => 'Создать пользователя',
    'Delete' => 'Удалить',
    'Email' => 'Электронная почта',
    'Fullname' => 'Имя пользователя',
    'ID' => 'Идентификатор',
    'Password' => 'Пароль',
    'Role' => 'Роль',
    'Update' => 'Редактировать пользователя',
    'Update Time' => 'Время обновления',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
    'User' => 'Пользователь',
    'Users' => 'Пользователи',

    'Deactivated' => 'Деактивирован',
    'Active' => 'Активный',
    'Status' => 'Статус',
    'Activation Date Time' => 'Дата активации',
    'Activation Time' => 'Дата активации',

    'Provider id' => 'Партнер',

    'Chat Enable' => 'Включить чат',
    'Upload avatar' => 'Загрузить аватар',
    'Avatar' => 'Аватар',

    'Picture' => 'Картинка',
    'Delete avatar' => 'Удалить аватар',
];
